/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package game;

/**
 *
 * @author Yassine
 */
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.util.Random;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
 
public class Main extends javax.swing.JFrame {
    int x = 190 ;
    int y =480;
    int yp =480;
    int i =1;
    int yy=-139;
    int xx=70;
    int life=3;
    String sc ;
    int carchoice ;
    int ex = 1 ;
    int ex1 = 1 ;
    int ex2 = 1 ;
    
    
    
    Random r = new Random ();
    /**
     * Creates new form Main
     */
    static boolean overlap(int p1 , int p2 , int p3 , int p4)
    {   
        
    return true ;
    }
    public Main() {
        
        initComponents();


    }




    



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        road = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        score = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/touringcar-white1.png"))); // NOI18N
        jLabel2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                jLabel2ComponentMoved(evt);
            }
        });
        jLabel2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel2KeyPressed(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, -140, 70, 140));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/minicarblue.png"))); // NOI18N
        jLabel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel1KeyPressed(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, 70, 140));

        road.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        road.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/cartrack.gif"))); // NOI18N
        getContentPane().add(road, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 360, 640));

        jPanel3.setBackground(new java.awt.Color(27, 217, 139));
        jPanel3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel3KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 640));

        jPanel4.setBackground(new java.awt.Color(27, 217, 139));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        jLabel3.setText("Lifes");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 100, 42));

        score.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        score.setText("3");
        score.setToolTipText("");
        jPanel4.add(score, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 69, 48));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 150, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel1KeyPressed
        // TODO add your handling code here:
        

    }//GEN-LAST:event_jLabel1KeyPressed

    private void jPanel3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel3KeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jPanel3KeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed

        
        if((evt.getKeyChar()=='q')&&(x-22>=39))
        {
            x-=22;
            jLabel1.setLocation(x, y);
        }
        else if ((evt.getKeyChar()=='d')&&(x+22<=340))
        {
            x+=22;
            jLabel1.setLocation(x, y);
        }

    }//GEN-LAST:event_formKeyPressed

    private void jLabel2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2KeyPressed

    private void jLabel2ComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel2ComponentMoved
        // TODO add your handling code here:
        yy+=4;
        jLabel2.setLocation(xx,yy);
        try {
            Thread.sleep(10);
        } catch (InterruptedException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
         if (life==3 && ex ==1)      
         {carchoice = r.nextInt(3)+1;
           System.out.println(carchoice);
       switch (carchoice){
           case 1 ->  {jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/yellow (1).png"))) ; }
           case 2 ->  {jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/4x4-blue1.png"))) ; }
           case 3 ->  {jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/touringcar-white1.png"))) ; }
           
       }
         ex = 0 ;}else if (life==2 && ex1 ==1)      
         {carchoice = r.nextInt(3)+1;
           System.out.println(carchoice);
       switch (carchoice){
           case 1 ->  {jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/yellow (1).png"))) ; }
           case 2 ->  {jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/4x4-blue1.png"))) ; }
           case 3 ->  {jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/touringcar-white1.png"))) ; }
           
       }
         ex1 = 0 ;}
                  
         else if (life==1 && ex2 ==1)      
         {carchoice = r.nextInt(3)+1;
           System.out.println(carchoice);
       switch (carchoice){
           case 1 ->  {jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/yellow (1).png"))) ; }
           case 2 ->  {jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/4x4-blue1.png"))) ; }
           case 3 ->  {jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/touringcar-white1.png"))) ; }
           
       }
         ex2 = 0 ;}
                  
       if (yy>=640)
       {     xx = r.nextInt(360)+40 ;
       carchoice = r.nextInt(3)+1;
           System.out.println(carchoice);
                   switch (carchoice){
           case 1 ->  {jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/yellow (1).png"))) ; }
           case 2 ->  {jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/4x4-blue1.png"))) ; }
           case 3 ->  {jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/touringcar-white1.png"))) ; }
           
       }
           yy=-140;}
        
       int x1a=jLabel1.getX() ;
       int y1a=jLabel1.getY()  ;
       int width1a=jLabel1.getWidth();
       int height1a=jLabel1.getHeight();
       int x2a=x1a+width1a;
       int y2a=y1a+height1a;
       
       
       int x1b=jLabel2.getX() ;
       int y1b=jLabel2.getY()  ;
       int width1b=jLabel2.getWidth();
       int height1b=jLabel2.getHeight();
       int x2b=x1b+width1b;
       int y2b=y1b+height1b;
       
       int xleft=Math.max(x1a, x1b);
       int xRight=Math.min(x2a, x2b);
       int xTop=Math.max(y1a, y1b);
       int xBottom=Math.min(y2a, y2b);
       
       if (xleft < xRight && xTop < xBottom)
       {
           int interwidth=xRight-xleft;
           int interheight=xBottom-xTop;
           int interarea=interwidth*interheight;
           if (interarea > 0)
           {   life--;
                if(life==0){
                End e = new End();
                e.show();
                dispose();
                }
                
                else if(life>0)
               {xx = r.nextInt(290)+40 ;
               yy=-140;
               
               score.setText(String.valueOf(life));}
               else dispose();
               
           }
           
       }


    }//GEN-LAST:event_jLabel2ComponentMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                
                new Main().setVisible(true);
         
            }
            
        });
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel road;
    private javax.swing.JLabel score;
    // End of variables declaration//GEN-END:variables
}
